apiVersion: v1
kind: Pod
metadata:
  name: express-container
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: hello-world
    image: express-hello-world:v1
    ports:
    - containerPort: 3000
